# Generated by Django 2.1.7 on 2019-04-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_player_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='owner',
            name='email',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='owner',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='owner',
            name='name',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='email',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
